### ISSUE TITLE
Not detecting fallen person

### ISSUE THREAD

**Issue by metalaman** [solbach/fallen-person-detector#2]
When I run the fallen_person_detector node it doesn't detect a fallen person.
For the following cloudGround point cloud(fallen person clearly visible),
![image](https://user-images.githubusercontent.com/8245954/36436324-edc61c8c-1689-11e8-878d-2b7d66ddd5e2.png)

I get the following CoG and UbC,

```
[ INFO] [1519144336.501612941]: CoG distance to ground: 2.911256m
[ INFO] [1519144336.501796666]: UbC distance to ground: 2.933364m

```
Also, to avoid getting 999999.0 CoG and UbC due to nan in body parts point cloud, I have removed them before the centroid is calculated.
I've commented out the piece of code which calculates Area and Volume, since I was getting a segmentation fault, and also these values aren't used anywhere, how can they be used for debugging purposes.

I also visualized extracted ground from cloudGround which wasn't as I expected(not representing the ground) and so I wanted to ask if there are some parameters that needs to be changed for the morphological filter, or does it work for specific environments.

Using Ubuntu 16.04, with OpenCV 3.2, CUDA 8.0 and Pepper Robot.
Any suggestions?
Thanks

**Comment by solbach** [comment]
Yes, the prediction is correct taking the numbers for _UbC_ and _CoG_ into account.
Looks like there is something wrong with your point cloud, especially with the 3D reprojection of your points. Have a look there and let me know if the numbers you get are feasible. For example, get the distance between wrist and elbow. That should be somewhere in the range of 40 - 70cm.
Also, check the intrinsic camera parameters whether they are set correctly to the camera you are using (if you use a zed stereo camera they get set automatically for you).

**Comment by metalaman** [comment]
Yup, I believe the issue is with depth transformation from 2D rectified image(Better depth calibration on my Asus Xtion would've worked). Anyway, a found a bad workaround for completely bypassing the entire Morphological filtering stage.
Closing the issue. Thanks.
